# Macro file for neutron_capture
#

##################### G4State_PreInit ###################

# ================== Analysis settings ==================

# Analysis parameters
/analysis/setFileName data/%%FileName%%
/analysis/setActivation true

# Switch on/off histograming
/analysis/setHistoDirName histograms
/analysis/h1/setActivationToAll true 

# Switch on/off ntupling
/analysis/setNtupleDirName ntuples
/analysis/ntuple/setActivationToAll true

# =================== Physics settings ==================

################## Kernel initialization ################

/run/initialize

#####################  G4State_Idle #####################

# ================== Verbose settings ==================

/analysis/verbose 0
/control/verbose 0
/process/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# =================== Physics settings ==================

/process/em/printParameters

# ==================== Phantom settings ====================

# Set concentration
/N1/geometry/SetConcentration %%Concentration%% %%ConcentrationUnit%%

# ==================== Beam settings ====================

# beam macro file
/gps/particle %%Particle%%
%%ConicalShapeBeam%%/control/execute beam/conical-beam.mac
%%BeamSpectrum%%/control/execute %%BeamSpectrumMacroFile%%
%%BeamMonoEnergy%%/gps/energy %%BeamEnergy%% %%BeamEneryUnit%%

# ==================== Beam settings ====================

# SetX Histos
/analysis/h1/setX 0 %%Histo1D0X%%
/analysis/h1/setX 1 %%Histo1D1X%%
/analysis/h1/setX 2 %%Histo1D2X%%
/analysis/h1/setX 3 %%Histo1D3X%%
/analysis/h1/setX 4 %%Histo1D4X%%
/analysis/h1/setX 5 %%Histo1D5X%%